/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ventanas;

import java.util.ArrayList;

/**
 *
 * @author Juan Seoane
 */
public class VentanaFundicion extends javax.swing.JFrame {

private boolean hecho = false;
private boolean cancelado = false;
private ArrayList<Integer > trimestres;
private int año;

    /**
     * Creates new form VentanaFundicion
     */
    public VentanaFundicion() {
        initComponents();
        rbtntrim0VF.setSelected(true);
        rbtntrim1VF.setSelected(true);
        rbtntrim2VF.setSelected(true);
        rbtntrim3VF.setSelected(true);
        rbtntrim4VF.setSelected(true);
        chbxFacturas.setSelected(true);
        chbxCajas.setSelected(true);
    }

    public boolean cancelado(){
        return cancelado;
    }
    
    public boolean hecho(){
        return hecho;
    }
    
    public void reset(){
        hecho = false;
        cancelado = false;
    }

    public ArrayList<Integer> getTrimestres() {
        return trimestres;
    }

    public int getAnho() {
        return año;
    }
    
    public boolean facturas(){
        if (chbxFacturas.isSelected())
            return true;
        else return false;
    }
    
     public boolean cajas(){
        if (chbxCajas.isSelected())
            return true;
        else return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAnhoVF = new javax.swing.JTextField();
        rbtntrim1VF = new javax.swing.JRadioButton();
        rbtntrim2VF = new javax.swing.JRadioButton();
        rbtntrim3VF = new javax.swing.JRadioButton();
        rbtntrim4VF = new javax.swing.JRadioButton();
        btnOKVF = new javax.swing.JButton();
        btnCancelVF = new javax.swing.JButton();
        rbtntrim0VF = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        chbxFacturas = new javax.swing.JCheckBox();
        chbxCajas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fundir Archivos");

        jLabel1.setText("INDIQUE EL AÑO :");

        jLabel2.setText("MARQUE LOS TRIMESTRES :");

        rbtntrim1VF.setText("1");

        rbtntrim2VF.setText("2");

        rbtntrim3VF.setText("3");

        rbtntrim4VF.setText("4");

        btnOKVF.setText("OK");
        btnOKVF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKVFActionPerformed(evt);
            }
        });

        btnCancelVF.setText("CANCEL");
        btnCancelVF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelVFActionPerformed(evt);
            }
        });

        rbtntrim0VF.setText("0");

        jLabel3.setText("FUNDIR :");

        chbxFacturas.setText("FACTURAS");

        chbxCajas.setText("CAJA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelVF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtntrim0VF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnhoVF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtntrim1VF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtntrim2VF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtntrim3VF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtntrim4VF)
                                        .addGap(0, 62, Short.MAX_VALUE))
                                    .addComponent(btnOKVF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbxFacturas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbxCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAnhoVF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtntrim1VF)
                    .addComponent(rbtntrim2VF)
                    .addComponent(rbtntrim3VF)
                    .addComponent(rbtntrim4VF)
                    .addComponent(rbtntrim0VF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chbxFacturas)
                    .addComponent(chbxCajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKVF)
                    .addComponent(btnCancelVF)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelVFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelVFActionPerformed
        this.cancelado = true;
    }//GEN-LAST:event_btnCancelVFActionPerformed

    private void btnOKVFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKVFActionPerformed
        trimestres = new ArrayList<Integer >();
        this.año = Integer.parseInt(txtAnhoVF.getText());
        if (rbtntrim0VF.isSelected())
            trimestres.add(0);
        if (rbtntrim1VF.isSelected())
            trimestres.add(1);
        if (rbtntrim2VF.isSelected())
            trimestres.add(2);
        if (rbtntrim3VF.isSelected())
            trimestres.add(3);
        if (rbtntrim4VF.isSelected())
            trimestres.add(4);
            
        this.hecho = true;
    }//GEN-LAST:event_btnOKVFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFundicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFundicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFundicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFundicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFundicion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelVF;
    private javax.swing.JButton btnOKVF;
    private javax.swing.JCheckBox chbxCajas;
    private javax.swing.JCheckBox chbxFacturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbtntrim0VF;
    private javax.swing.JRadioButton rbtntrim1VF;
    private javax.swing.JRadioButton rbtntrim2VF;
    private javax.swing.JRadioButton rbtntrim3VF;
    private javax.swing.JRadioButton rbtntrim4VF;
    private javax.swing.JTextField txtAnhoVF;
    // End of variables declaration//GEN-END:variables
}
