/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ventanas;

import modelo.*;
import modelo.base.Config;
import modelo.records.TipoGasto;
import ui.tablas.TablaFacturas_prev;

import javax.swing.JCheckBox;
import javax.swing.JComboBox;

/**
 *
 * @author juanseoane
 */
public class VentanaFiltros extends javax.swing.JFrame {

    private static VentanaFiltros instancia = null; 
    /**
     * Creates new form VentanaFiltros
     */
    private VentanaFiltros() {
        initComponents();
        cargarComboCategorias();
    }
    
    public static VentanaFiltros getVentana(){
        if (instancia == null)
            instancia = new VentanaFiltros();
        return instancia;
    }
    
    public boolean cargarComboCategorias(){
      for (TipoGasto tipo : Config.getConfig().getTiposGasto())  
        cmbCategoriasFiltros.addItem(tipo.tipo); 
      return true;
    }
    public String getFechaInicio(){
        return this.txtFechaDesdeFiltro.getText();
    }
    public String getFechaFinal(){
        return this.txtFechaHastaFiltro.getText();
    }
    public JCheckBox getChbFiltroCategoria() {
        return chbFiltroCategoria;
    }
    public String getFiltroDist(){
        return this.txtDistribuidorFiltro.getText().toUpperCase().trim();
    }
    public JCheckBox getChbFiltroDistribuidor() {
        return chbFiltroDistribuidor;
    }

    public JCheckBox getChbFiltroFecha() {
        return chbFiltroFecha;
    }

    public JComboBox getCmbCategoriasFiltros() {
        return cmbCategoriasFiltros;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chbFiltroFecha = new javax.swing.JCheckBox();
        chbFiltroDistribuidor = new javax.swing.JCheckBox();
        chbFiltroCategoria = new javax.swing.JCheckBox();
        txtFechaDesdeFiltro = new javax.swing.JTextField();
        txtDistribuidorFiltro = new javax.swing.JTextField();
        cmbCategoriasFiltros = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtFechaHastaFiltro = new javax.swing.JTextField();
        btnOKFiltros = new javax.swing.JButton();
        btnCancelFiltros = new javax.swing.JButton();

        setTitle("Filtros Facturas");

        chbFiltroFecha.setText("Fecha");

        chbFiltroDistribuidor.setText("Distribuidor");

        chbFiltroCategoria.setText("Categoría");

        jLabel1.setText("hasta el");

        btnOKFiltros.setText("OK");
        btnOKFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKFiltrosActionPerformed(evt);
            }
        });

        btnCancelFiltros.setText("Cancel");
        btnCancelFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chbFiltroDistribuidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbFiltroFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbFiltroCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDistribuidorFiltro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCategoriasFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFechaDesdeFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFechaHastaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOKFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbFiltroFecha)
                    .addComponent(txtFechaDesdeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaHastaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbFiltroDistribuidor)
                    .addComponent(txtDistribuidorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbFiltroCategoria)
                    .addComponent(cmbCategoriasFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKFiltros)
                    .addComponent(btnCancelFiltros)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFiltrosActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelFiltrosActionPerformed

    private void btnOKFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKFiltrosActionPerformed
        this.setVisible(false);
        TablaFacturas_prev.chkfiltros.setState(true);
        TablaFacturas_prev.setPulsado(5);
    }//GEN-LAST:event_btnOKFiltrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFiltros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFiltros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelFiltros;
    private javax.swing.JButton btnOKFiltros;
    private javax.swing.JCheckBox chbFiltroCategoria;
    private javax.swing.JCheckBox chbFiltroDistribuidor;
    private javax.swing.JCheckBox chbFiltroFecha;
    private javax.swing.JComboBox cmbCategoriasFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDistribuidorFiltro;
    private javax.swing.JTextField txtFechaDesdeFiltro;
    private javax.swing.JTextField txtFechaHastaFiltro;
    // End of variables declaration//GEN-END:variables
}
