/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ventanas;

/**
 *
 * @author Juan Seoane
 */
public class VentanaAutosave extends javax.swing.JFrame {

    public boolean cambio;
    public boolean fact;
    public boolean dist;
    public boolean caja;
    public boolean ok;
    /**
     * Creates new form VentanaAutosave
     */
    public VentanaAutosave() {
        super("COPIA DE SEGURIDAD");
        cambio = fact = dist = caja = ok = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkbxFacturas = new javax.swing.JCheckBox();
        chkbxDistribuidores = new javax.swing.JCheckBox();
        chkbxCaja = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkbxFacturas.setText("FACTURAS");
        chkbxFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxFacturasActionPerformed(evt);
            }
        });

        chkbxDistribuidores.setText("DISTRIBUIDORES");
        chkbxDistribuidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxDistribuidoresActionPerformed(evt);
            }
        });

        chkbxCaja.setText("CAJA");
        chkbxCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxCajaActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel1.setText("ELIJA DE QUÉ QUIERE HACER UNA COPIA DE SEGURIDAD:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkbxFacturas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkbxDistribuidores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkbxCaja))
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkbxFacturas)
                    .addComponent(chkbxDistribuidores)
                    .addComponent(chkbxCaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbxDistribuidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxDistribuidoresActionPerformed
       cambio = true;
        if (chkbxDistribuidores.isSelected())
           dist = true;
       else
           dist = false;
        cambio = false;
    }//GEN-LAST:event_chkbxDistribuidoresActionPerformed

    private void chkbxFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxFacturasActionPerformed
        cambio = true;
        if (chkbxFacturas.isSelected())
           fact = true;
       else
           fact = false;
        cambio = false;
    }//GEN-LAST:event_chkbxFacturasActionPerformed

    private void chkbxCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxCajaActionPerformed
        cambio = true;
        if (chkbxCaja.isSelected())
           caja = true;
       else
           caja = false;
        cambio = false;
    }//GEN-LAST:event_chkbxCajaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
         ok = true;
         System.out.println("Ventana: " + fact+" "+dist+" "+caja);
    }//GEN-LAST:event_btnOKActionPerformed
    
    public boolean ok(){
        return ok;
    }
    
    public boolean cambio(){
        return cambio;
    }
    
    public boolean fact(){
       return fact;
    }
    
    public boolean dist(){
        return dist;
    }
    
    public boolean caja(){
        return caja;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAutosave().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox chkbxCaja;
    private javax.swing.JCheckBox chkbxDistribuidores;
    private javax.swing.JCheckBox chkbxFacturas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
