/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ventanas;

import java.awt.Image;

/**
 *
 * @author Juan Seoane
 */
public class VentanaNotas extends javax.swing.JScrollPane {
    private Image icon;

    /**
     * Creates new form VentanaNotas
     */
    public VentanaNotas() {
        super();
        initComponents();
    }
    
    public javax.swing.JPanel getpanelprincipal(){
        return panelprincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        panelprincipal = new javax.swing.JPanel();

        this.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        this.setViewportView(panelprincipal);
        
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel panelprincipal;
//    public javax.swing.JScrollPane scrollpanelprincipal;
    // End of variables declaration//GEN-END:variables
}
