/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ventanas;

import modelo.*;
import modelo.records.NIF;
import modelo.records.RazonSocial;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanseoane
 */
public class VentanaDistribuidores extends javax.swing.JFrame {

    /**
     * Creates new form TablaDistribuidores
     */
    private ArrayList<RazonSocial> lista = new ArrayList<RazonSocial>();
    public RazonSocial razonseleccionada = null;
    public boolean seleccion = false;
    public boolean editar = false;
    public boolean salir = false;
    public boolean buscar = false;

    public VentanaDistribuidores() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonesDist = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnedicion = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollPanelDist = new javax.swing.JScrollPane();
        tablaDist = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana Distribuidores");
        setAlwaysOnTop(true);
        setFocusCycleRoot(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                emergenteWindowClosing(evt);
            }
        });

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnedicion.setText("Modo Edicion");
        btnedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedicionActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesDistLayout = new javax.swing.GroupLayout(panelBotonesDist);
        panelBotonesDist.setLayout(panelBotonesDistLayout);
        panelBotonesDistLayout.setHorizontalGroup(
            panelBotonesDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesDistLayout.createSequentialGroup()
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnedicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionar))
        );
        panelBotonesDistLayout.setVerticalGroup(
            panelBotonesDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesDistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addComponent(btnedicion)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBuscar))
        );

        tablaDist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDist.setFillsViewportHeight(true);
        scrollPanelDist.setViewportView(tablaDist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonesDist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanelDist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollPanelDist, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int filsel = -1;
        NIF nifsel;
        
        filsel = this.tablaDist.getSelectedRow();
        String nifst = this.tablaDist.getModel().getValueAt(filsel, 0).toString();
        if (nifst.indexOf("-")<3)
        {    
            String[] nifArray = nifst.split("-");
            int nifnum = Integer.parseInt(""+nifArray[1]+nifArray[2]);
            nifsel = new NIF(nifnum, nifArray[0],true);
        }
        else{
           String[] nifArray = nifst.split("-");
            nifsel = new NIF(Integer.parseInt(nifArray[0]), nifArray[1],false); 
        }
        //JOptionPane.showMessageDialog(null, "El NIF seleccionado es "+nifsel.getNumero());
        String nombre = this.tablaDist.getModel().getValueAt(filsel, 1).toString().trim();

        for (RazonSocial rs : this.lista) {
//            //System.out.println("Comparando Selección : "+nifsel.toString());
//            //System.out.println("con Distribuidor : "+rs.getNIF().toString());
            if ((nifsel.toString()).equals(rs.getNIF().toString())&& nombre.trim().equals(rs.getNombre().trim())) {
                this.razonseleccionada = rs;
                this.seleccion = true;
                break;
            }
            else {
//                JOptionPane.showMessageDialog(null,"No se ha encontrado el distribuidor\n"+nifsel.toString()+" "+nombre+ "\nen la base de distribuidores");
            }
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.seleccion = false;
        this.salir = true;
    }//GEN-LAST:event_btnSalirActionPerformed

    private void emergenteWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_emergenteWindowClosing
        this.salir = true;
    }//GEN-LAST:event_emergenteWindowClosing

    private void btnedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedicionActionPerformed
        this.editar = true;
    }//GEN-LAST:event_btnedicionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cargarTabla(this.lista);
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void cargarTabla(ArrayList<RazonSocial> listadistribuidores) {
        this.lista = listadistribuidores;
        Vector<Vector> datamodel = new Vector<Vector>();
        int i = -1;
        for (RazonSocial rs : listadistribuidores) {
            i++;
            Vector fila = new Vector();
            fila.add(((RazonSocial) listadistribuidores.get(i)).getNIF());
            fila.add(((RazonSocial) listadistribuidores.get(i)).getNombre());
            String filtro = txtBuscar.getText().toUpperCase();
            if (filtro.equals(""))
                datamodel.add(fila);
            else if ((listadistribuidores.get(i).getNIF().getNumero()+"").toUpperCase().contains(filtro) || (listadistribuidores.get(i).getNIF().getLetra()+"").toUpperCase().contains(filtro) || listadistribuidores.get(i).getNombre().toUpperCase().contains(filtro) || listadistribuidores.get(i).getRazon().toUpperCase().contains(filtro)){
                datamodel.add(fila);
            }
        }
        Vector colnames = new Vector();
        colnames.add("NIF");
        colnames.add("NOMBRE");
        DefaultTableModel modeloDist = new DefaultTableModel(datamodel, colnames);
        tablaDist.setModel(modeloDist);
    }

    public boolean seleccionado() {
        return this.seleccion;
    }

    public boolean editar() {
        return this.editar;
    }

    public boolean salir() {
        return this.salir;
    }

    public boolean buscar(){
        return this.buscar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDistribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDistribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDistribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDistribuidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDistribuidores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnedicion;
    private javax.swing.JPanel panelBotonesDist;
    private javax.swing.JScrollPane scrollPanelDist;
    private javax.swing.JTable tablaDist;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
