/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.visores;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;

import ui.ventanas.VentanaNotas;

/**
 *
 * @author juanseoane
 */
public class VisorNotas extends javax.swing.JFrame {

    /**
     * Creates new form VisorNotas
     */
    public VisorNotas() {
        super("VISOR DE NOTAS");
        initComponents();
    }
    
    public VentanaNotas getpanelfacturas(){
        return this.panelNotasFacturas;
    }
    
    public VentanaNotas getpaneldistribuidores(){
        return this.panelNotasRS;
    }
    
    public VentanaNotas getpanelCajas(){
        return this.panelNotasCaja;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setMinimumSize(new Dimension(600,300));
        
        JLabel etiquetaFact = new JLabel("Notas Facturas" , SwingConstants.CENTER);     
        panelNotasFacturas = new VentanaNotas();
        panelNotasFacturas.add(etiquetaFact);
        panelNotas.addTab("NOTAS FACTURAS",panelNotasFacturas);
        
        JLabel etiquetaRS = new JLabel("Notas Distribuidores" , SwingConstants.CENTER);
        panelNotasRS = new VentanaNotas();
        panelNotasRS.add(etiquetaRS);
        panelNotas.addTab("NOTAS DISTRIBUIDORES",panelNotasRS);
        
        JLabel etiquetaCaja = new JLabel("Notas Caja" , SwingConstants.CENTER);
        panelNotasCaja = new VentanaNotas();
        panelNotasCaja.add(etiquetaCaja);
        panelNotas.addTab("NOTAS CAJA",panelNotasCaja);
        
        this.getContentPane().add(panelNotas);
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisorNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisorNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisorNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisorNotas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    
  private JTabbedPane panelNotas = new JTabbedPane();
  private VentanaNotas panelNotasFacturas;
  private VentanaNotas panelNotasRS;
  private VentanaNotas panelNotasCaja;
    // End of variables declaration//GEN-END:variables
}
