<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sil.facturas</groupId>
        <artifactId>facturasSil</artifactId>
        <version>2.6</version>
    </parent>

    <artifactId>presentationgui</artifactId>
    <packaging>jar</packaging>

    <dependencies>

        <!-- Capa infrastructure -->
    <dependency>
        <groupId>com.sil.facturas</groupId>
        <artifactId>infrastructure</artifactId>
        <version>${project.version}</version>
    </dependency>

        <!-- Capa App -->
        <dependency>
            <groupId>com.sil.facturas</groupId>
            <artifactId>app</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- JavaFX -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>21.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>21.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>21.0.2</version>
        </dependency>

    </dependencies>

</project>
