/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.tablas;

import controladores.*;
import modelo.ModeloDistribuidores;
import java.awt.*;
import java.util.*;
import javax.swing.JCheckBox;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Seoane
 */
public class TablaDistribuidores extends javax.swing.JFrame {

    int indice = 0;
    static boolean hacambiado = false;
    static boolean filtrosactivos = false;
    public static int pulsado = 0;
    private Image icon;

    /**
     * Creates new form TablaDistribuidores
     */
    public TablaDistribuidores(Vector<Vector> datamodel, Vector colnames) {
        initComponents();
        startup();
        tablaDistribuidores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        rellenarTabla(datamodel, colnames);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        ListSelectionModel row = this.tablaDistribuidores.getSelectionModel();
        row.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                    filaSeleccionada();
            }
        });
        this.pack();
        this.setVisible(false);
    }

    private ArrayList<Image> startup(){
        
        icon = Toolkit.getDefaultToolkit().getImage("imagenes/tray.png");
        setIconImage(icon);
        ArrayList<Image> listaIconos = new ArrayList<Image>();
        
        listaIconos.add(icon);
        return listaIconos;
    }
    
    public int getIndice() {
        return indice;
    }

    public static void setPulsado(int num){
        pulsado = num;
        hacambiado = true;
    }
    
    public boolean haCambiado() {
        return hacambiado;
    }
    
    public static boolean filtrosactivos(){
        return filtrosactivos;
    }
    
    public void reset() {
        hacambiado = false;
        pulsado = 0;
    }

    public void rellenarTabla(Vector<Vector> datamodel, Vector colnames) {
        DefaultTableModel modelo = new DefaultTableModel(datamodel, colnames);
        tablaDistribuidores.setModel(modelo);

    }
    
    public void actualizarModelo(Vector distribuidores, int sel ){
        DefaultTableModel modelo = new DefaultTableModel(distribuidores,ModeloDistribuidores.getColumnas());
            
        tablaDistribuidores.setModel(modelo);
        
        ListSelectionModel selectionModel = tablaDistribuidores.getSelectionModel();
	selectionModel.setSelectionInterval(sel, sel);
        
    }
    
    public void filaSeleccionada() {
        
        ListSelectionModel selectionModel = tablaDistribuidores.getSelectionModel();
        indice = selectionModel.getLeadSelectionIndex();
//        JOptionPane.showMessageDialog(null,"Fila seleccionada  : " + (indice+1));
        if (indice <0)
            indice = 0;
//        hacambiado = true;
//        pulsado = 0;
    }
    
    public void formWindowClosing(java.awt.event.WindowEvent evt){
        ControladorDistribuidores.setEstado(0);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneTablaDistribuidores = new javax.swing.JScrollPane();
        tablaDistribuidores = new javax.swing.JTable();
        panelBotonesRS = new javax.swing.JPanel();
        btnfiltros = new javax.swing.JButton();
        chkbxfiltros = new javax.swing.JCheckBox();
        btneditarRS = new javax.swing.JButton();
        btnborrarRS = new javax.swing.JButton();
        btnimprimirRS = new javax.swing.JButton();
        btnverRS = new javax.swing.JButton();
        btnnuevaRS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tabla de Distribuidores");
        setAutoRequestFocus(false);
        setResizable(false);

        tablaDistribuidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDistribuidores.setFillsViewportHeight(true);
        scrollpaneTablaDistribuidores.setViewportView(tablaDistribuidores);
        tablaDistribuidores.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(scrollpaneTablaDistribuidores, java.awt.BorderLayout.CENTER);

        panelBotonesRS.setFocusCycleRoot(true);
        panelBotonesRS.setMaximumSize(new java.awt.Dimension(32767, 32));
        panelBotonesRS.setMinimumSize(new java.awt.Dimension(10, 32));
        panelBotonesRS.setName(""); // NOI18N
        panelBotonesRS.setPreferredSize(new java.awt.Dimension(0, 32));

        btnfiltros.setText("Filtros");
        btnfiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrosActionPerformed(evt);
            }
        });
        panelBotonesRS.add(btnfiltros);

        chkbxfiltros.setText("Filtros Activos");
        chkbxfiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxfiltrosActionPerformed(evt);
            }
        });
        panelBotonesRS.add(chkbxfiltros);

        btneditarRS.setText("Editar R.S.");
        btneditarRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarRSActionPerformed(evt);
            }
        });
        panelBotonesRS.add(btneditarRS);

        btnborrarRS.setText("Borrar R.S.");
        btnborrarRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarRSActionPerformed(evt);
            }
        });
        panelBotonesRS.add(btnborrarRS);

        btnimprimirRS.setText("PDF");
        btnimprimirRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirRSActionPerformed(evt);
            }
        });
        panelBotonesRS.add(btnimprimirRS);

        btnverRS.setText("Ver R.S.");
        btnverRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverRSActionPerformed(evt);
            }
        });
        panelBotonesRS.add(btnverRS);

        btnnuevaRS.setText("Nueva R.S.");
        btnnuevaRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevaRSActionPerformed(evt);
            }
        });
        panelBotonesRS.add(btnnuevaRS);

        getContentPane().add(panelBotonesRS, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevaRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevaRSActionPerformed
        pulsado = 1;
        hacambiado = true;
    }//GEN-LAST:event_btnnuevaRSActionPerformed

    private void btnverRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverRSActionPerformed
        pulsado = 2;
        hacambiado = true;
    }//GEN-LAST:event_btnverRSActionPerformed

    private void btnimprimirRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirRSActionPerformed
        pulsado = 3;
        hacambiado = true;
    }//GEN-LAST:event_btnimprimirRSActionPerformed

    private void btnborrarRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarRSActionPerformed
        pulsado = 4;
        hacambiado = true;
    }//GEN-LAST:event_btnborrarRSActionPerformed

    private void btneditarRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarRSActionPerformed
        pulsado = 5;
        hacambiado = true;
    }//GEN-LAST:event_btneditarRSActionPerformed

    private void btnfiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrosActionPerformed
        pulsado = 6;
        hacambiado = true;
    }//GEN-LAST:event_btnfiltrosActionPerformed

    private void chkbxfiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxfiltrosActionPerformed
        if (((JCheckBox)evt.getSource()).isSelected())
           filtrosactivos = true;
        else
            filtrosactivos = false;
        pulsado = 7;
        hacambiado = true;
    }//GEN-LAST:event_chkbxfiltrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrarRS;
    private javax.swing.JButton btneditarRS;
    private javax.swing.JButton btnfiltros;
    private javax.swing.JButton btnimprimirRS;
    private javax.swing.JButton btnnuevaRS;
    private javax.swing.JButton btnverRS;
    public static javax.swing.JCheckBox chkbxfiltros;
    private javax.swing.JPanel panelBotonesRS;
    private javax.swing.JScrollPane scrollpaneTablaDistribuidores;
    private javax.swing.JTable tablaDistribuidores;
    // End of variables declaration//GEN-END:variables
}
