/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.formularios;

import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import modelo.base.Config;
import modelo.helpers.Calculadora;
import modelo.records.Concepto;
import modelo.records.EntradaCaja;
import modelo.records.Fecha;
import modelo.records.Nota;

/**
 *
 * @author Juan Seoane
 */
public class FormularioCaja extends javax.swing.JFrame {

    private static FormularioCaja instancia = null;
    private boolean cambiado = false;
    private boolean hecho = false;
    private boolean cerrar = false;
    private int estado;
    public static final int INSERTAR = 0;
    public static final int EDITAR = 1;

    /**
     * Creates new form FormularioCaja
     */
    private FormularioCaja() {
        initComponents();
        initControls();
    }

    public static FormularioCaja getFormulario() {
        if (instancia == null) instancia = new FormularioCaja();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        gbtndebehaber = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtCajaDia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCajaAnho = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCajaMes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCajaCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbOrigenCaja = new javax.swing.JComboBox();
        btnHaber = new javax.swing.JRadioButton();
        btnDebe = new javax.swing.JRadioButton();
        btnCalc = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCajaOK = new javax.swing.JButton();
        btnCajaCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();

        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("DD");

        jLabel5.setText("€");

        jLabel3.setText("AAAA");

        jLabel2.setText("MM");

        jLabel4.setText("CANTIDAD : ");

        jLabel12.setText("ORIGEN : ");

        cmbOrigenCaja.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmbOrigenCajaActionPerformed(evt);
                }
            }
        );

        gbtndebehaber.add(btnHaber);
        btnHaber.setText("HABER");

        gbtndebehaber.add(btnDebe);
        btnDebe.setText("DEBE");

        btnCalc.setText("Calc");
        btnCalc.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCalcActionPerformed(evt);
                }
            }
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel1Layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(
                                    jPanel1Layout
                                        .createSequentialGroup()
                                        .addComponent(btnHaber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDebe)
                                        .addPreferredGap(
                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE
                                        )
                                        .addComponent(btnCalc)
                                )
                                .addGroup(
                                    jPanel1Layout
                                        .createSequentialGroup()
                                        .addGroup(
                                            jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                    jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                        )
                                                        .addComponent(
                                                            txtCajaDia,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            35,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                        )
                                                        .addComponent(jLabel2)
                                                )
                                                .addComponent(
                                                    jLabel4,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    83,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                                )
                                                .addComponent(jLabel12)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                            jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCajaCantidad)
                                                .addGroup(
                                                    jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addComponent(
                                                            txtCajaMes,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            36,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                        )
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                        )
                                                        .addComponent(
                                                            txtCajaAnho,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            80,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                )
                                                .addComponent(
                                                    cmbOrigenCaja,
                                                    0,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE
                                                )
                                        )
                                )
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addContainerGap()
                )
                .addComponent(
                    lblDate,
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE
                )
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel1Layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(
                                    txtCajaDia,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jLabel2)
                                .addComponent(
                                    txtCajaMes,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jLabel3)
                                .addComponent(
                                    txtCajaAnho,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(
                            jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnHaber)
                                .addComponent(btnDebe)
                                .addComponent(btnCalc)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(
                            jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(
                                    txtCajaCantidad,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(
                            jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(
                                    cmbOrigenCaja,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jLabel12)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(
                            lblDate,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            16,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                )
        );

        btnCajaOK.setText("GUARDAR");
        btnCajaOK.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCajaOKActionPerformed(evt);
                }
            }
        );

        btnCajaCancel.setText("CERRAR");
        btnCajaCancel.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCajaCancelActionPerformed(evt);
                }
            }
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    jPanel2Layout
                        .createSequentialGroup()
                        .addComponent(btnCajaCancel)
                        .addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE
                        )
                        .addComponent(btnCajaOK)
                )
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    jPanel2Layout
                        .createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(
                            jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCajaOK)
                                .addComponent(btnCajaCancel)
                        )
                )
        );

        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane1.setViewportView(txtNota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                    jPanel2,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE
                )
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addComponent(
                            jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addGap(0, 0, Short.MAX_VALUE)
                )
                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1).addContainerGap())
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addComponent(
                            jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(
                            jPanel2,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                )
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void initControls() {
        this.txtCajaAnho.setText(Config.getConfig().getAnho().getAnho() + "");
        /** TODO : AÑADIR A LA CONFIG EL TIPO DE RETENCION EN LOS INGRESOS */
        this.gbtndebehaber.setSelected(null, hecho);
        for (Concepto c : Config.getConfig().getOrigenesCaja()) this.cmbOrigenCaja.addItem(c.getOrigen());
        this.cmbOrigenCaja.addItem("AÑADIR NUEVO");
        this.estado = INSERTAR;
    }

    private void btnCajaOKActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCajaOKActionPerformed
        this.hecho = true;
        this.cambiado = true;
    } //GEN-LAST:event_btnCajaOKActionPerformed

    private void btnCajaCancelActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCajaCancelActionPerformed
        this.cerrar = true;
        this.cambiado = true;
    } //GEN-LAST:event_btnCajaCancelActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCalcActionPerformed
        Calculadora calc = new Calculadora("Calculadora");
        calc.setVisible(true);
    } //GEN-LAST:event_btnCalcActionPerformed

    private void cmbOrigenCajaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cmbOrigenCajaActionPerformed
        if (this.cmbOrigenCaja.getSelectedItem().equals("AÑADIR NUEVO")) nuevoConcepto();
    } //GEN-LAST:event_cmbOrigenCajaActionPerformed

    public boolean nuevoConcepto() {
        String nuevo = JOptionPane.showInputDialog(null, "Introduzca el nuevo concepto:");
        if (!nuevo.trim().equals("")) {
            this.cmbOrigenCaja.addItem(nuevo.toUpperCase().trim());
            ArrayList<Concepto> lista = Config.getConfig(Config.getConfig().usuario).getOrigenesCaja();
            lista.add(new Concepto(nuevo.toUpperCase().trim()));
            Config.getConfig().setOrigenesCaja(lista);
            if (Config.recConfig(Config.getConfig().getUsuario(), Config.getConfig())) return true; else return false;
        }
        JOptionPane.showMessageDialog(null, "El Concepto no se ha guardado!");
        return false;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public void limpiarFormulario() {
        this.txtCajaDia.setText("");
        this.txtCajaMes.setText("");
        this.txtCajaAnho.setText(Config.getConfig().getAnho().getAnho() + "");
        this.lblDate.setText(new GregorianCalendar().getTime() + "");
        this.txtCajaCantidad.setText("");
        /** TODO : AÑADIR A LA CONFIG EL TIPO DE RETENCION EN LOS INGRESOS */
        this.cmbOrigenCaja.setSelectedIndex(0);
        this.txtNota.setText("");
    }

    public void rellenarFormulario(EntradaCaja c) {
        this.txtCajaDia.setText(c.getFecha().getDia() + "");
        this.txtCajaMes.setText(c.getFecha().getMes() + "");
        this.txtCajaAnho.setText(c.getFecha().getAnho() + "");
        this.txtCajaCantidad.setText(c.getCaja() + "");
        this.lblDate.setText(c.getDate() + "");
        if (c.isHaber()) {
            btnHaber.setSelected(true);
            btnDebe.setSelected(false);
        } else {
            btnHaber.setSelected(false);
            btnDebe.setSelected(true);
        }
        /** TODO : AÑADIR A LA CONFIG EL TIPO DE RETENCION EN LOS INGRESOS */
        this.cmbOrigenCaja.setSelectedItem(c.getOrigen());
        this.txtNota.setText(c.getNota().getTexto());
    }

    public EntradaCaja recogerFormulario() {
        try {
            EntradaCaja nuevaCaja;
            int dia = Integer.parseInt(this.txtCajaDia.getText());
            int mes = Integer.parseInt(this.txtCajaMes.getText());
            int anho = Integer.parseInt(this.txtCajaAnho.getText());
            String origen = cmbOrigenCaja.getSelectedItem().toString();
            String nota = txtNota.getText();
            boolean haber;
            double cantidad = Double.parseDouble(this.txtCajaCantidad.getText());
            if (btnDebe.isSelected()) {
                cantidad = cantidad;
                haber = false;
                nuevaCaja =
                    new EntradaCaja(
                        0,
                        new Fecha(dia, mes, anho),
                        new GregorianCalendar().getTime(),
                        origen,
                        cantidad,
                        haber,
                        new Nota(nota)
                    );
                return nuevaCaja;
            } else if (btnHaber.isSelected()) {
                cantidad = cantidad;
                haber = true;
                nuevaCaja =
                    new EntradaCaja(
                        0,
                        new Fecha(dia, mes, anho),
                        new GregorianCalendar().getTime(),
                        origen,
                        cantidad,
                        haber,
                        new Nota(nota)
                    );
                return nuevaCaja;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha habido un error en la recogida de datos!");
        }
        return null;
    }

    public boolean cambiado() {
        return this.cambiado;
    }

    public boolean hecho() {
        return this.hecho;
    }

    public boolean cerrar() {
        return this.cerrar;
    }

    public void reset() {
        this.hecho = false;
        this.cerrar = false;
        this.cambiado = false;
        this.estado = INSERTAR;
        limpiarFormulario();
    }

    public void visible(boolean bool) {
        this.reset();
        this.setVisible(bool);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger
                .getLogger(FormularioCaja.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger
                .getLogger(FormularioCaja.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger
                .getLogger(FormularioCaja.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                .getLogger(FormularioCaja.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
            new Runnable() {
                public void run() {}
            }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCajaCancel;
    private javax.swing.JButton btnCajaOK;
    private javax.swing.JButton btnCalc;
    private javax.swing.JRadioButton btnDebe;
    private javax.swing.JRadioButton btnHaber;
    private javax.swing.JComboBox cmbOrigenCaja;
    private javax.swing.ButtonGroup gbtndebehaber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtCajaAnho;
    private javax.swing.JTextField txtCajaCantidad;
    private javax.swing.JTextField txtCajaDia;
    private javax.swing.JTextField txtCajaMes;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
}
